name: My_First_Workflow

on:
  push:
    branches:
      - master

jobs:
  first_test:
    runs-on: ubuntu-latest

    steps:
      - name: echo_hello_world
        uses: actions/checkout@v4
        run: echo "Hello, World!"
