name: My_First_Workflow

on:
  push:
    branches:
      - main

jobs:
  first_test:
    runs-on: ubuntu-latest

    steps:
      - name: github-checkout
        uses: actions/checkout@v4
        
      - name: echo_hello_world
        run: echo "Hello, World!"

      - name: get_folder_contents
        run: ls -a

      - name: retrieve_env_var
        run: echo ${{ secrets.DONALD }}

      - name: retrieve_secret
        run: echo ${{ secrets.SECRET_DONALD }}
