name: My_First_Workflow

on:
  push:
    branches:
      - main

jobs:
  first_test:
    runs-on: ubuntu-latest

    steps:
      - name: github-checkout
        uses: actions/checkout@v4
      
      - name: get_folder_contents
        run: ls -a

      - name: poetry-install-and-configure
        uses: snok/install-poetry@v1
        with:
          version: 2.1.3
          virtualenvs-in-project: true
          virtualenvs-create: true
          poetry-no-interaction: true
          installer-parallel: true

      - name: activate-venv
        run: source .venv/bin/activate

      - name: install_packages
        run: poetry install

      - name: test_python
        run: uvicorn main:app --host=0.0.0.0 --port=8000
        
